<?php
/* ********************************************************************************
* The content of this file is subject to the VTEAuthnet("License");
* You may not use this file except in compliance with the License
* The Initial Developer of the Original Code is VTExperts.com
* Portions created by VTExperts.com. are Copyright(C) VTExperts.com.
* All Rights Reserved.
* ****************************************************************************** */
$languageStrings = array(

    /* For License page - Begin */
    'MODULE_LBL' => 'VTEAuthnet',
    'LBL_REQUIREMENTS' => 'Requirements',
    'LBL_LICENSING' => 'Licensing',
    'LBL_COMPLETE' => 'Complete',
    'LBL_WELCOME' => 'Welcome to the',
    'LBL_INSTALLATION_WIZARD' => 'Installation Wizard',
    'LBL_INSTALL' => 'Install',
    'LBL_THANK' => 'Thank you for purchasing the',
    'LBL_VTIGER_EXTENSION' => 'vTiger Extension!',
    'LBL_PRODUCT_REQUIRES' => 'The Product requires PHP-SOAP & IonCude Loader to function properly.',
    'LBL_PHPSOAP' => 'PHP-SOAP',
    'LBL_IONCUDE' => 'IonCude Loader',
    'LBL_INSTALLATION_INSTRUCTIONS' => 'Click here for Installation Instructions',
    'LBL_BOTH_PHP_EXT' => 'Both PHP Extensions are mandatory',
    'LBL_YOU_WILL_NOT' => 'You will not be abe to complete',
    'LBL_EXT_INSTALLATION' => 'Extension installation without them being installed first.',
    'LBL_HAVE_TROUBLE' => 'Having trouble installing?',
    'LBL_CONTACT_US' => 'Please Contact Us!',
    'LBL_EMAIL' => 'Email',
    'LBL_PHONE' => 'Phone',
    'LBL_CHAT' => 'Chat',
    'LBL_AVAILABLE_ON' => 'Available on',
    'LBL_YOU_ARE_REQUIRED_VALIDATE' => 'You are required to validate the extension before it can be use. Please enter the license key provided.',
    'LBL_VTIGER_URL' => 'vTiger URL:',
    'LBL_LICENSE_KEY' => 'License Key:',
    'LBL_LICENSE_EXPIRES' => 'License Expires:',
    'LBL_SUPPORT_EXPIRES' => 'Support Expires:',
    'LBL_ACTIVATE' => 'Activate',
    'LBL_HAVING_TROUBLE' => 'Having trouble? Please Contact Us!',
    'LBL_ORDER_NOW' => 'Order Now',
    'LBL_FINISH' => 'Finish',
    'LBL_EXPIRES_ON' => 'Expires on',
    'LBL_EXPIRED_ON' => 'Expired on',
    'LBL_LICENSE_UPGRADE' => 'License & Upgrade',
    'LBL_UPGRADE' => 'Upgrade',
    'LBL_RELEASE_LICENSE' => 'Release License',
    'LBL_INSTALLATION_COMPLETED' => 'The Installation Completed Successfully!',
    'LBL_FEEL_FREE_CONTACT' => 'If you have any questions or run into any issues - feel free to contact us.',
    'LBL_HAS_BEEN_SUCCESSFULLY' => 'has been installed & activated successfully!',
    'LBL_MORE_EXTENSIONS' => 'For more vTiger Extensions, please visit our website',
    /* For License page - End */

    'LBL_PAYMENTS_LIST_VIEW' => 'Payments',
    'LBL_PAYMENTS_LIST_VIEW_DESC' => 'List of all payments that have been created. Payments are found on the invoice by clicking <strong>"Payments"</strong> button. The list consists of all payments, including scheduled, unpaid, paid, automatically created and so on.<br /><br />',
    'LBL_CUSTOMERS_LIST_VIEW' => 'Customers',
    'LBL_CUSTOMERS_LIST_VIEW_DESC' => 'List of Customer profiles in Authorize.net. The list only includes very basic information and authorize.net IDs for troubleshooting purposes. You should not create customer profiles by going to this list. The only way to create customer profiles is from the <strong>Organization > More > Authorize.Net Integration</strong> area.<br /><br />',
    'LBL_PAYMENTPROFILE_LIST_VIEW' => 'Payment Profiles',
    'LBL_PAYMENTPROFILE_LIST_VIEW_DESC' => 'List of payment profiles in Authorize.net. We do not keep any of the sensitive information such as card details. All the sensitive information is stored in Authorize.net. These profiles are the bridge between VTiger and Authorize.net. You should not create payment profiles by going to this list. The only way to create payment profiles is from the <strong>Organization > More > Authorize.Net Integration</strong> area. The list is only available for troubleshooting purposes.<br /><br />',
    'LBL_TRANSACTION_LIST_VIEW' => 'Transactions Log',
    'LBL_TRANSACTION_LIST_VIEW_DESC' => 'List of all transactions generated by Authorize.net. All the successful and failed charges will show up as a transaction. This list is only for informational and troubleshooting purposes.<br /><br />',
    'LBL_API_DETAIL_ALERT_INFO' => 'NOTE: Instructions on how to obtain keys & configure the integration is available at documentation area. </br></br>Link: <a href="https://www.vtexperts.com/helpdesk/authorize-net/" target="_blank">https://www.vtexperts.com/helpdesk/authorize-net/</a>',
    'ModuleFieldLabel' => 'ModuleFieldLabel Text',
    'MODULE_MANAGEMENT' => 'Module Management',
    'TAB_INTEGRATE_AUTHORIZE_NET' => 'Authorize.Net Integration Settings',
    'LBL_INTEGRATE_AUTHORIZE_NET_STATUS' => 'Enable Authorize.Net',
    'LBL_MERCHANT_LOGIN_ID' => 'Merchant Login ID',
    'LBL_MERCHANT_TRANSACTION_KEY' => 'Merchant Transaction Key',
    'LBL_AUTHORIZE_NET_MODE' => 'Authorize.Net Mode',
    'LBL_AUTHORIZE_NET_MODE_SANBOX' => 'SanBox',
    'LBL_AUTHORIZE_NET_MODE_PRODUCTION' => 'Production',
    'LBL_SELECT_AN_OPTION' => 'Select an Option',
    'LBL_VALIDATION_MODE' => 'Validation Mode',
    'LBL_VALIDATION_MODE_TEST_MODE' => 'Test Mode',
    'LBL_VALIDATION_MODE_LIVE_MODE' => 'Live Mode',
    'LBL_DOWNLOAD' => 'Download',

    'LBL_FOLDERS_AND_FILES' => 'Folder(s) & Files',
    'LBL_QUERIES_STATEMENT' => 'Queries',
    'LBL_UNINSTALL' => 'UnInstall',
    'LBL_LINK_UNINSTALL' => 'Uninstall',
    'LBL_AUTHNET_LIB_MISSING' => 'Click on <strong><a href="javascript:Settings_ANCustomers_Js.downloadAuthNetLib();">Download</a></strong> button to download and install Authorize.net Library script and to progress in installation. Please be patient it may take a while.<br /><br />In case that you are unable to automatically download Authorize.net Library, you can donwload it manually from <pre>https://www.vtexperts.com/files/AN.zip</pre> and unzip it into <pre>~VTIGER_ROOT/modules/ANCustomers/libs/</pre>',
);

$jsLanguageStrings = array(
    'JS_INTEGRATE_AUTHORIZE_NET_MODE_REQUIRED' => 'Authorize.Net Mode is required',
    'JS_INTEGRATE_AUTHORIZE_NET_VALIDATION_MODE_REQUIRED' => 'Authorize.Net Validation Mode is required',
    'JS_INTEGRATE_AUTHORIZE_NET_MERCHANT_LOGIN_ID_REQUIRED' => 'Authorize.Net Merchant Login ID is required',
    'JS_INTEGRATE_AUTHORIZE_NET_MERCHANT_TRANSACTION_KEY_REQUIRED' => 'Authorize.Net Merchant Transaction Key is required',
);
