<?php


//This is the access privilege file
$is_admin=true;

$user_info=array('user_name'=>'admin','is_admin'=>'on','user_password'=>'$1$fe000000$RkK5PvzBTq./R10b0vmPn.','confirm_password'=>'$1$fe000000$RkK5PvzBTq./R10b0vmPn.','first_name'=>'Omni','last_name'=>'CRM','roleid'=>'H18','email1'=>'admin@omniscientcrm.com','status'=>'Active','activity_view'=>'Today','lead_view'=>'Today','hour_format'=>'24','end_hour'=>'','start_hour'=>'06:00','title'=>'CEO','phone_work'=>'669-231-2464','department'=>'OMNI Group','phone_mobile'=>'408-316-0370','reports_to_id'=>'','phone_other'=>'408-971-2928','email2'=>'felipeluna2000@yahoo.com','phone_fax'=>'669-231-2464','secondaryemail'=>'fluna2000@gmail.com','phone_home'=>'408-971-2928','date_format'=>'mm-dd-yyyy','signature'=>'&lt;span style=&quot;font-family:arial, helvetica, sans-serif;&quot;&gt;Felipe Luna, CEO&lt;br /&gt;
Omniscient&lt;br /&gt;
669-231-2464&lt;br /&gt;&lt;a href=&quot;http://omniscientcrm.com&quot;&gt;www.omniscientcrm.com&lt;/a&gt;&lt;/span&gt;','description'=>'entered by Felipe','address_street'=>'1900 The Alameda, 1st Floor','address_city'=>'San Jose','address_state'=>'Ca','address_postalcode'=>'95126','address_country'=>'USA','accesskey'=>'vW6MiyBQVSfQjt3o','time_zone'=>'America/Los_Angeles','currency_id'=>'1','currency_grouping_pattern'=>'123,456,789','currency_decimal_separator'=>'.','currency_grouping_separator'=>',','currency_symbol_placement'=>'$1.0','imagename'=>'blk_and_wht_felipe_2.jpg','internal_mailer'=>'1','theme'=>'nature','language'=>'en_us','reminder_interval'=>'Turn Off','asterisk_extension'=>'','use_asterisk'=>'0','mail_password'=>'Consec8439','mail_username'=>'felipeluna','mail_servername'=>'localhost','advisor_control_number'=>'','ops_specialist_id'=>'0','active_directory'=>'1','default_record_view'=>'Summary','callduration'=>'10','dayoftheweek'=>'Monday','othereventduration'=>'30','calendarsharedtype'=>'selectedusers','veo_username'=>'','veo_password'=>'Consec11','my_groups'=>'','exchange_enabled'=>'1','exchange_information'=>'','rowheight'=>'wide','no_of_currency_decimals'=>'2','truncate_trailing_zeros'=>'0','leftpanelhide'=>'0','defaulteventstatus'=>'Planned','defaultactivitytype'=>'Call','hidecompletedevents'=>'0','is_owner'=>'','reminder_popup'=>'1','reminder_email'=>'1','user_logo'=>'','accessible_ids'=>'','omniscient_control_number'=>'','deleted'=>'0','upn'=>'felipeluna@omnisrv.com','defaultcalendarview'=>'MyCalendar','default_documents_folder_id'=>'73439617','turn_of_confirmation'=>'1','show_hidden_folders'=>'1','documents_default_view'=>'List','currency_name'=>'USA, Dollars','currency_code'=>'USD','currency_symbol'=>'&#36;','conv_rate'=>'1.00000','record_id'=>'','record_module'=>'','id'=>'1186');

?>