<?php


//This is the access privilege file
$is_admin=true;

$user_info=array('user_name'=>'admin','is_admin'=>'on','user_password'=>'$1$ad000000$LOOm9jWuS1BRcgjYMqz881','confirm_password'=>'$1$ad000000$LOOm9jWuS1BRcgjYMqz881','first_name'=>'Omni','last_name'=>'AI','roleid'=>'H104','email1'=>'AI@Omnisrv.com','status'=>'Active','activity_view'=>'Today','lead_view'=>'Today','hour_format'=>'12','end_hour'=>'23:00','start_hour'=>'08:00','title'=>'AI','phone_work'=>'669-231-2400','department'=>'Omniscient','phone_mobile'=>'669-231-2400','reports_to_id'=>'1186','phone_other'=>'','email2'=>'info@omnisrv.com','phone_fax'=>'669-231-2400','secondaryemail'=>'admin@omnisrv.com','phone_home'=>'','date_format'=>'mm-dd-yyyy','signature'=>'','address_street'=>'1900 The Alameda
Suite 100','address_city'=>'San Jose','address_state'=>'Ca','address_postalcode'=>'95126','address_country'=>'','accesskey'=>'rV8daZto5LQj779','time_zone'=>'America/Los_Angeles','currency_id'=>'1','currency_grouping_pattern'=>'123,456,789','currency_decimal_separator'=>'.','currency_grouping_separator'=>',','currency_symbol_placement'=>'$1.0','imagename'=>'Omni_logo_Transparent_PNG.png','internal_mailer'=>'1','theme'=>'rainbow','language'=>'en_us','reminder_interval'=>'5 Minutes','asterisk_extension'=>'','use_asterisk'=>'0','mail_password'=>'89453611','ops_specialist_id'=>'0','active_directory'=>'0','default_record_view'=>'Summary','callduration'=>'10','dayoftheweek'=>'Monday','othereventduration'=>'60','calendarsharedtype'=>'selectedusers','veo_password'=>'test123456','my_groups'=>'','rowheight'=>'medium','no_of_currency_decimals'=>'2','truncate_trailing_zeros'=>'1','leftpanelhide'=>'0','defaulteventstatus'=>'Planned','defaultactivitytype'=>'Call','hidecompletedevents'=>'0','is_owner'=>'1','reminder_popup'=>'0','reminder_email'=>'0','user_logo'=>'','deleted'=>'0','defaultcalendarview'=>'MyCalendar','default_documents_folder_id'=>'24920947','turn_of_confirmation'=>'1','show_hidden_folders'=>'1','documents_default_view'=>'List','business_hours'=>'','appointment_url'=>'','15min'=>'','30min'=>'','1hr'=>'','brochure_file'=>'','brochure_shorturl'=>'','currency_name'=>'USA, Dollars','currency_code'=>'USD','currency_symbol'=>'&#36;','conv_rate'=>'1.00000','record_id'=>'','record_module'=>'','id'=>'1');

?>