<?php
/* ********************************************************************************
* The content of this file is subject to the VTEAuthnet("License");
* You may not use this file except in compliance with the License
* The Initial Developer of the Original Code is VTExperts.com
* Portions created by VTExperts.com. are Copyright(C) VTExperts.com.
* All Rights Reserved.
* ****************************************************************************** */
$languageStrings = array(
	'Account Name' => 'Organization Name',
	'LBL_ANPAYMENTPROFILE_INFORMATION' => 'Authorize.Net Payment Profile Information',
    'SINGLE_ANPaymentProfile' => 'Authorize.Net Payment Profile',
    'individual' => 'Individual',
    'business' => 'Business',
    'CreditCardSimpleType' => 'Credit Card',
    'BankAccountType' => 'Bank Account',
    'checking' => 'Checking',
    'savings' => 'Savings',
    'businessChecking' => 'Business Checking',
    'ACCOUNT_ID_TOOLTIP' => 'Organization Name',
    'CUSTOMER_PROFILE_ID_TOOLTIP' => '',
    'CUSTOMER_TYPE_TOOLTIP' => 'The type of customer associated with the transaction: Individual or Business.',
    'PAYMENT_METHOD_TOOLTIP' => 'Based on selection, you will be able to enter credit card or bank details at the bottom. *Bank requires e-Check.net to be enabled on your Authorize.net account.',
    'ASSIGNED_USER_ID_TOOLTIP' => 'Assigned To',
    'DESCRIPTION_TOOLTIP' => 'Description',
    'FIRSTNAME_TOOLTIP' => 'First Name of the card holder or customer name.',
    'LASTNAME_TOOLTIP' => 'Last Name of the card holder or customer name.',
    'ADDRESS_TOOLTIP' => '',
    'CITY_TOOLTIP' => '',
    'STATE_TOOLTIP' => '',
    'ZIP_TOOLTIP' => '',
    'COUNTRY_TOOLTIP' => '',
    'PHONE_NUMBER_TOOLTIP' => '',
    'FAX_NUMBER_TOOLTIP' => '',
    'AN_ID_TOOLTIP' => 'ID generated by Authorize.net. It can be used to locate payment profile in Authorize.net panel',
    'CARD_NUMBER_TOOLTIP' => '',
    'EXPIRATION_DATE_TOOLTIP' => '',
    'CARD_CODE_TOOLTIP' => '',
    'ACCOUNT_TYPE_TOOLTIP' => '',
    'ROUTING_NUMBER_TOOLTIP' => '',
    'ACCOUNT_NUMBER_TOOLTIP' => '',
    'NAME_ON_ACCOUNT_TOOLTIP' => '',
    'E_CHECK_TYPE_TOOLTIP' => "<ul style='text-align: left;'><li><b>ARC - Accounts Receivable Conversion: </b>This transaction type is a one-time charge against a customer's checking account. ARC allows merchants to collect payments received in the mail or left in a drop-box, and convert them to an electronic payment. When you use this eCheck type, NACHA requires that you use a Magnetic Ink Character Recognition Reader to provide proof of a paper check.</li><li><b>BOC - Back Office Conversion: </b>This transaction type is a one-time charge against a customer's checking account. BOC allows merchants to collect a check written at a point of sale (checkout counter, manned bill payment location, service call location) and convert it to an ACH debit during back office processing. When you use this eCheck type, NACHA requires that you use a Magnetic Ink Character Recognition Reader to provide proof of a paper check.</li><li><b>CCD - Cash Concentration or Disbursement: </b>This transaction type is a one-time or recurring charge or refund against a business checking account. CCD transactions are fund transfers to or from a corporate entity.</li><li><b>PPD - Prearranged Payment and Deposit Entry: </b>This transaction type is a one-time or recurring charge or refund against a consumer checking or savings account. PPD transactions may only be originated when payment and deposit terms between the merchant and the customer are prearranged.</li><li><b>TEL - Telephone-Initiated Entry: </b>This transaction type is a one-time charge against a consumer checking or savings account that was originated by telephone. TEL transactions can only be originated when an existing relationship between the merchant and the customer exists; or if no relationship exists, the customer must initiate the telephone call to the merchant.</li><li><b>WEB - Internet-Initiated Entry: </b>This transaction type is a one-time or recurring charge against a consumer checking or savings account and for which payment authorization was obtained from the customer via the Internet.</li></ul>
",
    'BANK_NAME_TOOLTIP' => '',
    'IS_PRIMARY_TOOLTIP' => 'This is used for automated billing. If payment is scheduled and there are multiple payment profiles available, the "Primary" payment profile will be used.',
    'BILLING_INFORMATION_TOOLTIP' => 'Address is used to process transactions. The more accurate the address, the more likely transaction will get approved.',
    'LBL_EXPIRATION_MONTH' => 'Month',
    'LBL_EXPIRATION_YEAR' => 'Year',
    'Primary' => 'Primary',
    'CREDIT_CARD_INFORMATION_EDIT_PAYMENT_BTN_TOOLTIP' => 'You can update customer and address information without reentering credit card/bank information. To make changes to credit card/bank details - click Edit Payment Details.',
    'BANK_INFORMATION_EDIT_PAYMENT_BTN_TOOLTIP' => 'You can update customer and address information without reentering credit card/bank information. To make changes to credit card/bank details - click Edit Payment Details.',
    'LBL_EDIT_PAYMENT_DETAIL_BTN' => 'Edit Payment Details',
);

$jsLanguageStrings = array(

);
