<?php
/**
 * Created by PhpStorm.
 * User: Ryan
 * Date: 2016-07-16
 * Time: 4:52 PM
 */

class ModSecurities_yql_View extends Vtiger_Detail_View{
    public function process(Vtiger_Request $request)
    {
        echo "TESTING";
//        return parent::process($request); // TODO: Change the autogenerated stub
    }
}